# Generated by Django 3.2.8 on 2021-10-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment_hour',
            name='week',
            field=models.CharField(choices=[('0', 'Geçmiş Hafta'), ('1', 'Bu Hafta'), ('2', 'Gelecek Hafta')], default='-1', max_length=1, verbose_name='Hafta'),
        ),
    ]
