# Generated by Django 3.2.8 on 2021-10-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_hour_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment_hour',
            name='week',
            field=models.CharField(blank=True, choices=[('0', 'Geçmiş Hafta'), ('1', 'Bu Hafta'), ('2', 'Gelecek Hafta')], max_length=1, null=True, verbose_name='Hafta'),
        ),
    ]
